apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      initContainers:
      - name: "{{ .Chart.Name }}-init"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ['/bin/sh', '-c', 'npx prisma migrate up --auto-approve --experimental']
        env:
        - name: GDFORMS_DATABASEURL
          value: "postgresql://postgres:password@{{ .Chart.Name }}-postgres-pgpool/postgres"
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ['yarn', 'start']
        env:
        - name: GDFORMS_DATABASEURL
          value: "postgresql://postgres:password@{{ .Chart.Name }}-postgres-pgpool/postgres"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}